### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 45: invalid start byte

### ISSUE THREAD

**Issue by jeenhyung** [craigfrancis/audio-detect#1]
Hi

I got a error message below when I input "python ./process.py ./aaa.mp3 ./samples/ 0.75" command.

> Traceback (most recent call last):
  File "./process.py", line 38, in <module>
    exec(open(config_path).read(), config)
  File "/opt/anaconda3/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 45: invalid start byte

How fix this?

**Comment by craigfrancis** [comment]
Sorry, the readme file was out of date (now corrected).

The first argument is now for a config file, because I was finding it difficult to keep track of all the arguments this script can take.

I think that should resolve this issue, but please re-open if not.
