### ISSUE TITLE
AttributeError: module 'librosa.display' has no attribute 'waveplot'.

### ISSUE THREAD

**Issue by milahu** [craigfrancis/audio-detect#10]
process.sample.py + librosa version 0.9.2

**Comment by craigfrancis** [comment]
Note to self:

https://github.com/craigfrancis/audio-detect/blob/main/process.samples.py#L133

Looks like `librosa.display.waveplot()` has been removed, maybe use `waveshow()`?

https://librosa.org/doc/0.10.0/generated/librosa.display.waveshow.html

Ref v0.8.1: "librosa.display.waveplot is now deprecated in favor of librosa.display.waveshow", [issue 1207](https://github.com/librosa/librosa/issues/1207).

**Comment by craigfrancis** [comment]
Thanks @milahu.

If you update the project, hopefully it will work now (please re-open if that's not the case).

Ref commit https://github.com/craigfrancis/audio-detect/commit/94aa2a34a3e9047e333a3a70a6500da5e626b5ab.
