### ISSUE TITLE
Can I use mp4 video instead of mp3?

### ISSUE THREAD

**Issue by jonburchel** [craigfrancis/audio-detect#11]
Can I use mp4 video instead of mp3? I want to generate video clips with detected sounds in video. Thanks for creating this tool!

**Comment by craigfrancis** [comment]
I’ve not tried, but if memory serves MP4 is just a container format, where the audio is contained within it… so it might just work (unfortunately I’m not at my computer today).

For some detail, “pcm_data” uses ffmpeg to get the audio (and it’s usually pretty good at working out what to do)… if it doesn’t, it might be possible to tweak `process.source.py` (probably line 24)… or if that fails, just extract the audio before running?

I’ll close for now, but if you have any problems, maybe host the video somewhere (so I can download and try it), and let me know the details.

**Comment by jonburchel** [comment]
I'll try it out! Thanks for your contribution to the community. 💖
