### ISSUE TITLE
File not found - windows

### ISSUE THREAD

**Issue by FlorinBoho** [craigfrancis/audio-detect#6]
I am getting this error when I try to run the command
 
`python3 E:\Desktop\audio-detect-main\process.py E:\Desktop\Protv\config.py E:\Desktop\output.mp3`

![image](https://user-images.githubusercontent.com/17811390/100517051-bf54f600-3190-11eb-9a17-f867d6c6eb23.png)

and I have no idea what to do, have you got any tips?

**Comment by FlorinBoho** [comment]
This is the content of the used files, and I looked through it but I can't understand why it can't find the file specified.

![image](https://user-images.githubusercontent.com/17811390/100517152-6afe4600-3191-11eb-9bc5-1334373cdf07.png)

**Comment by craigfrancis** [comment]
I’m not at a computer at the moment, so can’t be sure, but I suspect it might be the difference between MS Windows paths using a backslash in paths, whereas the systems I use (MacOS and Linux) all use a forward slash... so maybe my code needs updating to use the correct one.

**Comment by FlorinBoho** [comment]
I read about paths here https://stackoverflow.com/questions/2953834/windows-path-in-python and I found out that I can use / for both Windows and Linux, or \\ for Windows.

I modified the path accordingly but it seems it still does not work. The issue is from the pcm_data() call as seen here 
![image](https://user-images.githubusercontent.com/17811390/100520384-27fa9d80-31a6-11eb-92cf-fdb7aeba32d8.png)

Looks like the parameter passing in pcm_data() should work with no issues as it's a string. 
I am still confused what's the cause of this error.

![image](https://user-images.githubusercontent.com/17811390/100520741-1adeae00-31a8-11eb-8db9-91b26f9d1c62.png)

**Comment by craigfrancis** [comment]
Do you have ffmpeg installed? I wonder if it can’t find and execute it?

**Comment by FlorinBoho** [comment]
You were right, it was all from ffmpeg. 

Because on windows, simply typing ffmpeg in CMD will give you an error. Happened the same with pyhton3 until I installed it from windows store. 

You have to give it the full path to ffmpeg, like this so it works. 
![image](https://user-images.githubusercontent.com/17811390/100521870-1ec1fe80-31af-11eb-95dc-b0f6393df93b.png)

To fix this, you can add in config.py another line config['ffmpeg-location']=Path-to-ffmpeg.exe



Now I am stuck on another issue and I am trying to figure it out.
Have you got any tips for this issue?
![image](https://user-images.githubusercontent.com/17811390/100521902-72cce300-31af-11eb-9265-febbe8eef19f.png)

**Comment by craigfrancis** [comment]
It’s been a long time since I’ve looked at this code, can you check that `series` contains something... if memory serves this is a value that comes from ffmpeg.

**Comment by FlorinBoho** [comment]
Yes, `series` is empty.

I looked behind and apparently it's an issue in pcm_data(). 
For Load Source, it works.
For Load Samples, it doesn't.

I will use it with one sample only and try to find a solution in the meantime, I will come back if nothing will work in the end.

Thank you. 
![image](https://user-images.githubusercontent.com/17811390/100523826-1fad5d00-31bc-11eb-99ea-59723a79973d.png)

**Comment by craigfrancis** [comment]
I wonder if it’s the path thing again (forward vs back slash), as the samples come from a folder (concatenated), whereas the source is provided in full.

**Comment by FlorinBoho** [comment]
I think it is the path again, and that it takes all the files in the folder even if they are not .mp3 files.
Besides this, it adds a `\ `even if the path that I use is with `/`.

In my case, it also takes the `config.py` file, I will put it in another folder and try again (in your read.me file, you also had config.py in the samples folder)

![image](https://user-images.githubusercontent.com/17811390/100550833-500cfe00-3285-11eb-8ca8-142748fe7e74.png)

**Comment by FlorinBoho** [comment]
I solved it by modifying the highlighted line in the above reply by adding `'/*.mp3'`, instead of leaving it like `'/*'`

![image](https://user-images.githubusercontent.com/17811390/100551208-df1b1580-3287-11eb-92cc-0faf2f3b2476.png)

And it works perfectly :) 
Now I just need to work with it further and have it display information in the place that I need to.

Thank you very much for the tips so far, the problem has been solved.

**Comment by craigfrancis** [comment]
Thanks for raising these issues @FlorinBoho 

I've just made some quick changes, so the scripts use `os.path.join()` for path related work, and there is a new `'ffmpeg_path'` config variable.

I've not tested these on Windows, so please re-open this issue if it's still not right.
