### ISSUE TITLE
Length of matching sample?

### ISSUE THREAD

**Issue by mc510** [craigfrancis/audio-detect#7]
Are there any constraints on the length of the matching sample? The example uses 0.7 seconds; can the sample be longer? Presumably longer samples would have lower probability of false positives, but are there limits to how long the matching sample can be?

**Comment by craigfrancis** [comment]
No limits - but you’re right, if the sample is longer, it’s likely to differ, and not match.

You should also tweak the `matching_min_score` to help.

But the other thing to remember is processing time - if there are lots of candidates, they are all being checked, it can take a while (I had a 3 hour audio file, and depending on the samples and config, the processing time went anywhere between 5 minutes to 5 hours).
