### ISSUE TITLE
Add a LICENSE file?

### ISSUE THREAD

**Issue by ssokolow** [craigfrancis/audio-detect#8]
Without a declared license, you're [basically saying](https://choosealicense.com/no-permission/) "By agreeing to GitHub's Terms of Service, I gave permission for you to look at any source I uploaded, but I haven't given you permission to use it".

Would you mind adding one?

GitHub's own https://choosealicense.com/ is the simplest way to pick a license that matches the terms you want and auto-generate a pull request to add a `LICENSE` file.

(Note that any code you borrowed from elsewhere must stay under the license you got it under, unless the license you want to add is a superset. For example, you can use MIT code in a GPL project because the MIT doesn't forbid adding more rules as long as you continue to comply with the existing ones and the GPL's terms are a struct superset of the MIT license's terms... though you still have to obey those terms, which typically means leaving the copyright notices and license declarations intact on the borrowed bits.)

**Comment by craigfrancis** [comment]
Good point, I've added BSD 3-Clause.

**Comment by craigfrancis** [comment]
Oh, and thanks for noticing.
